[project]
name = "n-cmapss-dl"
version = "0.1.0"
description = "N-CMAPSS dataset for DL"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.2.5",
    "scikit-learn>=1.6.1",
    "torch>=2.7.0",
]
